[package]
name = "parol-app"
edition.workspace = true

[[bin]]
name = "parol-app"
path = "app.rs"

[dependencies]
parol_runtime = "3.0.0"

[dev-dependencies]
parol = "4.0.0"
snapbox = "0.6.21"

[lints]
workspace = true
