[package]
name = "chumsky-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "chumsky-app"
path = "app.rs"

[dependencies]
ariadne = "0.3.0"
#chumsky = "1.0.0-alpha.6"
chumsky = { git = "https://github.com/zesterer/chumsky.git" }
